from ntm.schema import Question


def legit_etl(session):
    questions = [
        Question(
            filename="1.jpeg",
            correct_option="Diego Calb",
            false_option1="Ciro Zar",
            false_option2="Martin Dran",
            false_option3="Tomas Pastore",
        ),
        Question(
            filename="2.jpg",
            correct_option="Joaquin Torre",
            false_option1="Francisco Lopez Destain",
            false_option2="Javier Di Santo",
            false_option3="Stefano Marcaccio",
        ),
        Question(
            filename="3.jpg",
            correct_option="Pablo Navarro",
            false_option1="Ivan Terzano",
            false_option2="Bruno Sarverry",
            false_option3="Mariano Re",
        ),
        Question(
            filename="4.png",
            correct_option="Martin Cura",
            false_option1="Mateo De Monasterio",
            false_option2="Diego Calb",
            false_option3="Taiel Colavecchia",
        ),
        Question(
            filename="5.jpg",
            correct_option="Erik Ernst",
            false_option1="Santiago Balay",
            false_option2="Diego Calb",
            false_option3="Javier Caceres",
        ),
        Question(
            filename="6.jpg",
            correct_option="Francisco Murias",
            false_option1="Agustin Ramirez Rojas",
            false_option2="Diego Leguizamon",
            false_option3="Dante Pawlow",
        ),
        Question(
            filename="7.jpg",
            correct_option="Cintia Mancinelli",
            false_option1="Franca Mascolo",
            false_option2="Marian Pachon",
            false_option3="Aldana Mercado",
        ),
        Question(
            filename="8.jpeg",
            correct_option="Douglas Carmona",
            false_option1="Tomas Ramos",
            false_option2="Pablo Lorenzatto",
            false_option3="Diego Calb",
        ),
        Question(
            filename="9.jpg",
            correct_option="Macarena Olivieri",
            false_option1="Aldana Mercado",
            false_option2="Marianela Paniagua",
            false_option3="Marian Pachon",
        ),
        Question(
            filename="10.png",
            correct_option="Pablo Lorenzatto",
            false_option1="Joaquin Torre",
            false_option2="Francisco Murias",
            false_option3="Nicolas Buzzano",
        ),
        Question(
            filename="11.jpeg",
            correct_option="Marcelo Costamagna",
            false_option1="Diego Leguizamon",
            false_option2="Facundo Palavecino",
            false_option3="Federico Rosende",
        ),
        Question(
            filename="12.png",
            correct_option="Robinson Fang",
            false_option1="Aldo Escobar",
            false_option2="Pablo Navarro",
            false_option3="Douglas Carmona",
        ),
        Question(
            filename="13.jpg",
            correct_option="Juan Marchese",
            false_option1="Facundo Bianco",
            false_option2="Agustin Merlinsky",
            false_option3="Ezequiel Fattori",
        ),
        Question(
            filename="14.jpg",
            correct_option="Karla Castillo",
            false_option1="Cintia Mancinelli",
            false_option2="Lucia Kasman",
            false_option3="Aldana Mercado",
        ),
        Question(
            filename="15.jpg",
            correct_option="Aldana Mercado",
            false_option1="Karla Castillo",
            false_option2="Paula Lima",
            false_option3="Marian Pachon",
        ),
        Question(
            filename="16.jpeg",
            correct_option="Guido Turturici",
            false_option1="Alejadro Rosano",
            false_option2="Damian Valdamarin",
            false_option3="Guido Trucco",
        ),
        Question(
            filename="17.jpeg",
            correct_option="Franca Mascolo",
            false_option1="Marianela Paniagua",
            false_option2="Cintia Mancinelli",
            false_option3="Francisco Murias",
        ),
        Question(
            filename="18.jpg",
            correct_option="Alejandro Rosano",
            false_option1="Cristian Antuña",
            false_option2="Juan Martin Pampliega",
            false_option3="Ignacio Vago",
        ),
        Question(
            filename="19.jpg",
            correct_option="Lucia Perez",
            false_option1="Lucia Kasman",
            false_option2="Macarena Olivieri",
            false_option3="Melissa Campbell",
        ),
        Question(
            filename="20.jpeg",
            correct_option="Alejandro Rusi",
            false_option1="Joaquin Torre",
            false_option2="Erik Ernst",
            false_option3="Tomas Ramos",
        ),
        Question(
            filename="21.jpg",
            correct_option="Bruno Sarverry",
            false_option1="Hugo Viotti",
            false_option2="Javier Balonga",
            false_option3="Ivan Terzano",
        ),
        Question(
            filename="22.jpeg",
            correct_option="Tomas Ramos",
            false_option1="Juan Marchese",
            false_option2="Ivan Pupkin",
            false_option3="Leo Mansini",
        ),
        Question(
            filename="23.png",
            correct_option="Gonzalo Villafañe",
            false_option1="Hernan Vignolo",
            false_option2="Pedro Ferrari",
            false_option3="Juan Alric",
        ),
        Question(
            filename="24.png",
            correct_option="Ivan Terzano",
            false_option1="Gonzalo Villafañe",
            false_option2="Pablo Lorenzatto",
            false_option3="Francisco Murias",
        ),
        Question(
            filename="25.jpeg",
            correct_option="Hugo Viotti",
            false_option1="Ciro Zar",
            false_option2="Rodrigo Ramos",
            false_option3="Ezequiel Malamud",
        ),
        Question(
            filename="26.jpg",
            correct_option="Taiel Colavecchia",
            false_option1="Tomas Ramos",
            false_option2="Erik Ernst",
            false_option3="Martin Cura",
        ),
        Question(
            filename="27.jpeg",
            correct_option="Agustina Etchebehere",
            false_option1="Lucia Perez",
            false_option2="Paula Lima",
            false_option3="Victoria Zolezzi",
        ),
        Question(
            filename="28.jpeg",
            correct_option="Santiago Donikian",
            false_option1="Mateo de Monasterio",
            false_option2="Alejandro Rusi",
            false_option3="Erik Ernst",
        ),
        Question(
            filename="29.jpg",
            correct_option="Magali Gerbasi",
            false_option1="Victoria Azcarate",
            false_option2="Victoria Zolezzi",
            false_option3="Agustina Etchebehere",
        ),
        Question(
            filename="30.jpg",
            correct_option="Juan Martin Pampliega",
            false_option1="Ivan Terzano",
            false_option2="Ivan Pupkin",
            false_option3="Tomas Ramos",
        ),
        Question(
            filename="31.jpeg",
            correct_option="Mateo De Monasterio",
            false_option1="Santiago Donikian",
            false_option2="Nicolas Bucardo",
            false_option3="Santiago Stachuk",
        ),
        Question(
            filename="32.jpeg",
            correct_option="Aldo Escobar",
            false_option1="Mariano Re",
            false_option2="Augusto Peña",
            false_option3="Ignacio Vago",
        ),
        Question(
            filename="final.jpg",
            correct_option="The fourth one",
            false_option1="The first one",
            false_option2="The second one",
            false_option3="The third one",
        ),
    ]
    for question in questions:
        session.merge(question)
    session.commit()
